# Workflows that run integration tests on live sites

name: Integration tests
run-name: Integration tests for ${{ github.event.inputs.springfield_service_hostname || 'https://prod.eu.springfield.prod.webservices.mozgcp.net' }} at ${{ inputs.git_sha || github.sha }}
on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch of mozmeao/springfield we're testing against - main|stage|prod|run-integration-tests
        required: false
      git_sha:
        description: The git SHA just deployed to the service we want to test
        required: false
      springfield_service_hostname:
        description: The root URL of the service to run tests against
        required: false
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - LABEL: faux-saucelabs
            BROWSER_NAME: chrome
            DRIVER: Remote
            MARK_EXPRESSION: smoke
          - LABEL: test-headless
            DRIVER: ""
            MARK_EXPRESSION: headless

    env:
      BASE_URL: ${{ github.event.inputs.springfield_service_hostname || 'https://prod.eu.springfield.prod.webservices.mozgcp.net' }}
      BROWSER_NAME: ${{ matrix.BROWSER_NAME }}
      CI_JOB_ID: ${{ github.run_id }}
      DRIVER: ${{ matrix.DRIVER }}
      LABEL: ${{ matrix.LABEL }}
      MARK_EXPRESSION: ${{ matrix.MARK_EXPRESSION }}
      PLATFORM: ""
      PYTEST_PROCESSES: auto
      SAUCELABS_API_KEY: " "
      SAUCELABS_USERNAME: " "

    # Note we use if: always() below to keep things going, rather than
    # continue-on-error, because that approach falsely marks the overall
    # test suite as green/passed even if it has some failures.

    steps:
      - name: Fetch codebase
        if: always()
        uses: actions/checkout@v4
      - name: Sets specific env vars IF we're on testing against dev/main only
        if: ${{ github.event.inputs.branch == 'main'}}
        run: |
          echo "BOUNCER_URL=https://bouncer-bouncer.stage.mozaws.net/" >> $GITHUB_ENV

      - name: Run functional integration tests
        if: always()
        run: ./bin/integration_tests/functional_tests.sh
        env:
          TEST_IMAGE: mozmeao/springfield_test:${{ inputs.git_sha || 'latest' }}  # ${{ github.event.inputs.git_sha }}

      - name: Cleanup after functional integration tests
        if: always()
        run: ./bin/integration_tests/cleanup_after_functional_tests.sh

      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results-${{github.run_id}}-${{matrix.label}}
          if-no-files-found: ignore  # this avoids a false "Warning" if there were no issues

  playwright-tests:
    if: always()
    runs-on: ubuntu-latest
    env:
      PLAYWRIGHT_BASE_URL: ${{ github.event.inputs.springfield_service_hostname || 'https://prod.eu.springfield.prod.webservices.mozgcp.net' }}
      CI: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: cd tests/playwright && npm ci && npm run install-deps
    - name: Run Playwright tests
      run: cd tests/playwright && npm run integration-tests
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results-${{ github.event.inputs.git_sha }}-${{ github.run_id }}
        path: tests/playwright/test-results/
        if-no-files-found: ignore  # this avoids a false "Warning" if there were no issues
        retention-days: 30
