name: Unit tests
on:
  push:
    branches:
      - test

jobs:
  test-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build media"
        run: |
            npm ci
            npm run build
      - name: "Run collectstatic"
        run: |
            docker compose run assets python manage.py collectstatic --noinput
